'use client';

import React, { useEffect, useState } from 'react';
import NewHeader from '../../components/homepage/NewHeader';
import Footer from '../../components/homepage/Footer';
import '../globals.css'; 
import WhatsAppButton from './components/whatsappbutton';
import TopBar from '../../components/homepage/topbar';

const CustomerLayout = ({ children }) => {
  const [isClient, setIsClient] = useState(false);
  const [pixelCode, setPixelCode] = useState('');
  const [contactinfo,setcontactinfo]=useState([])

  useEffect(() => {
    setIsClient(true);

    // Fetch the first Facebook Pixel code
    const fetchPixelCode = async () => {
      try {
        const response = await fetch('/api/pixels');
        const data = await response.json();
        if (data?.data?.length > 0) {
          setPixelCode(data.data[0].pixelCode); // Set the first pixel code
        }
      } catch (error) {
        console.error('Error fetching pixel code:', error);
      }
    };

    fetchPixelCode();
  }, []);

  const [companyName, setcompanyName]=useState('');
  const [companyHeaderImage, setcompanyHeaderImage]=useState('');
  const [companyicon, setcompanyicon]=useState('');
  useEffect(() => {
    async function fetchCompanyDetails() {
      console.log("Fetching company details...");
      try {
        const response2 = await fetch('/api/contactinfo');
        const newdata = await response2.json();
        setcontactinfo(newdata[0]);
        console.log("COnttact details are: ",newdata);
        const response = await fetch('/api/companydetails');
        const data = await response.json();
        console.log("Fetched data:", data);
        if (data) {
          console.log("data is : ",data);
          setcompanyName(data.name);
          setcompanyHeaderImage(data.headerImage);
          setcompanyicon(data.favIcon);
          console.log("Company data is ",company);
         
        }
      } catch (error) {
        console.error('Error fetching company details:', error);
      }
    }
    fetchCompanyDetails();
  }, []);

  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{companyName}</title>
        <link rel="icon" href={`${process.env.NEXT_PUBLIC_UPLOADED_IMAGE_URL}/${companyicon}`} />
        <meta name="description" content="Generated by create next app" />
        {pixelCode && (
          <script
            dangerouslySetInnerHTML={{
              __html: `
                !function(f,b,e,v,n,t,s)
                {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
                n.callMethod.apply(n,arguments):n.queue.push(arguments)};
                if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
                n.queue=[];t=b.createElement(e);t.async=!0;
                t.src=v;s=b.getElementsByTagName(e)[0];
                s.parentNode.insertBefore(t,s)}(window,document,'script',
                'https://connect.facebook.net/en_US/fbevents.js');
                fbq('init', '${pixelCode}'); 
                fbq('track', 'PageView');
              `,
            }}
          />
        )}
      </head>
      <body>
        <div className="min-h-screen bg-white flex flex-col">
        {/* <TopBar phone={contactinfo.phoneNumber} email={contactinfo.email} name={companyName} /> */}
          <NewHeader image={companyHeaderImage} phone={contactinfo.phoneNumber} email={contactinfo.email}/>
          <main className="flex-grow">
            {isClient && <WhatsAppButton />}
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default CustomerLayout;
